### ISSUE TITLE
新功能筹备

### ISSUE THREAD

**Issue by zswang** [zswang/jdists#2]
### 处理 CommonJS 依赖模块

```html
<!--replace encoding="require" base="../src" insert="_moduleId = '{{source}}';"-->
require("core/utils");
<!--/replace-->
```

### 常用打包工具的插件

* grunt
* fis
* gulp

**Comment by zswang** [comment]
fis 插件：https://github.com/fex-team/fis-postprocessor-region
gulp 插件：https://github.com/zswang/gulp-jdists

**Comment by techird** [comment]
佩服大叔的执行力！

**Comment by raiscui** [comment]
感谢大神的掉渣天神器, 请问能否支持 sourcemap?
